# yaml-language-server: $schema=./charts/redis/values.schema.json
architecture: standalone
auth:
  existingSecret: redis-password-secret
  existingSecretPasswordKey: redis-password
master:
  extraVolumes:
    - name: redis-secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: redis-spc
  extraVolumeMounts:
    - name: redis-secrets-store-inline
      mountPath: "/mnt/secrets"
      readOnly: true
  tolerations:
    - key: "kubernetes.azure.com/scalesetpriority"
      operator: "Equal"
      value: "spot"
      effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: "kubernetes.azure.com/scalesetpriority"
                operator: In
                values:
                  - "spot"
