apiVersion: v1
kind: Service
metadata:
  name: {{.Values.deployment.name}}-svc
  labels:
    app: {{.Values.deployment.name}}
  annotations:
    {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ports:
  - port: {{.Values.service.port | default 6379}}
    targetPort: 6379
    protocol: TCP
  selector:
      app: {{.Values.deployment.name}}
  type: {{.Values.service.type}}